name: testando i-f
on:
  workflow_dispatch:
  push:
    branches-ignore: #ignorar somente branchs da lista:
      - main
    
jobs:
  build_primeiro_commit:
    name: Buildando o app e testando o IF
    runs-on: ubuntu-latest
    #if: ${{ contains(github.event.head_commit.message, 'primeiro commit') }}
    #if: "contains(github.event.head_commit.message, 'primeiro commit'"
    steps:
      - uses: actions/checkout@v2
      - name: 1ยบ commit
        if: ${{ contains(github.event.head_commit.message, 'primeiro commit') }}
        run: echo "buildando com primeiro commit."
      - name: 2ยบ commit ou mais
        if: ${{ !contains(github.event.head_commit.message, 'primeiro commit') }}
        run: |
          echo "buildando com segundo commit ou mais.."
        
        
  
  #build_segundo_commit_ou_mais:
  #  name: build commit 2 ou mais
  #  runs-on: ubuntu-latest
  #  if: ${{ !contains(github.event.head_commit.message, 'primeiro commit') }}
  #  steps:
   #   - name: 2ยบ commit ou mais
   #     run: |
    #          echo "buildando com segundo commit ou mais."
