name: testando i-f
on:
  workflow_dispatch:
  push:
    #branches-ignore: #ignorar somente branchs da lista:
     # - main
    
jobs:
  build_primeiro_commit:
    name: Buildando o app e testando o IF
    runs-on: ubuntu-latest
    #if: ${{ contains(github.event.head_commit.message, 'primeiro commit') }}
    #if: "contains(github.event.head_commit.message, 'primeiro commit'"
    steps:
      
      - uses: actions/checkout@v2
      - name: Verify initial commit
        id: initial_commit_check
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          if [ "$COMMIT_MESSAGE" == "initial commit" ]; then
          echo "initial_commit=true" >> $GITHUB_ENV
          else
          echo "This is not the initial commit."
          exit 1
          fi
          
      - name:  commit
        run: echo ${{env.initial_commit}}
       #if: steps.initial_commit_check.outputs.status == 'success'
      - name: 1ยบ commit
        if: ${{ env.initial_commit }}
        run: echo "buildando com primeiro commit."
      - name: 2ยบ commit ou mais
        if: ${{ !env.initial_commit }}
        run: |
          echo "buildando com segundo commit ou mais..."
        
        
  
  #build_segundo_commit_ou_mais:
  #  name: build commit 2 ou mais
  #  runs-on: ubuntu-latest
  #  if: ${{ !contains(github.event.head_commit.message, 'primeiro commit') }}
  #  steps:
   #   - name: 2ยบ commit ou mais
   #     run: |
    #          echo "buildando com segundo commit ou mais."
